main_site = 'http://qa-scooter.praktikum-services.ru/'
courier_api = main_site + 'api/v1/courier'
login_courier_api = main_site + 'api/v1/courier/login'
orders_api = main_site + '/api/v1/orders'
orders_api_cancel = main_site + '/api/v1/orders/cancel'
